### ISSUE TITLE
How to add more languages?

### ISSUE THREAD

**Issue by Qiangong2** [Timwi/EsotericIDE#2]
Is there an easy way to add more languages than just coding the languages in? Also, Will there be syntax highlighting on the languages at all?

**Comment by Timwi** [comment]
I think coding the languages in is pretty much the easiest way I could make it. It’s already fairly easy; just look at some of the existing implementations to get an idea of how it’s structured.

Syntax highlighting is not currently on the radar, but if you find a text-editor component that supports it and runs within WinForms that you like, feel free to experiment with it and show it to me! :)
