### ISSUE TITLE
Ubuntu Compatible?

### ISSUE THREAD

**Issue by NonlinearFruit** [Timwi/EsotericIDE#3]
How can I run this on Ubuntu (or Linux in general)? I'm not familiar with C# or Mono. Any ideas?

**Comment by Timwi** [comment]
I’m not familiar with Mono either, but it should work just fine if you install Mono and run it (pass it the exe file). Esoteric IDE doesn’t use any features that aren’t fully supported by Mono to my knowledge.

**Comment by NonlinearFruit** [comment]
Running the exe with Ubuntu's default Mono gives a unhandled `System.IO.FileNotFoundException`. This is solved [here](https://github.com/KSP-CKAN/CKAN/issues/516) by installing **mono-complete**. I tried it and it solved that error, but now  I get a unhandled `System.Reflection.TargetInvocationException`. Any ideas?

Here are some relevant bits of the stack trace:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: XOR data length expected 2046820352, read 370
Parameter name: stream
... 
  at EsotericIDE.Resources.get_EsotericIDEIcon () <0x41f592f0 + 0x0003e> in <filename unknown>:0 
  at EsotericIDE.Mainform..ctor (EsotericIDE.Settings settings) <0x41edb6e0 + 0x00087> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) EsotericIDE.Mainform:.ctor (EsotericIDE.Settings)
  at EsotericIDE.EsotericIDEProgram.Main (System.String[] args) <0x41e94930 + 0x001b7> in <filename unknown>:0
```

**Comment by Timwi** [comment]
The exception stacktrace suggests this is a bug in Mono’s handling of file-embedded resources.
