### ISSUE TITLE
Open File from command line

### ISSUE THREAD

**Issue by knthb** [Timwi/EsotericIDE#6]
It would be nice if you could add the ability to call your application from the command line with the first parameter as a filename, and have EsoIDE open that file, e.g.
`%USERPROFILE%\Documents\E\EsotericIDE\EsotericIDE.exe %CD%\helloworld.bf`
This would make it easier to programatically open files, and make it so one could associate your IDE with its respective filetypes.

**Comment by Timwi** [comment]
Implemented. Many thanks for the suggestion!
