### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by knthb** [Timwi/EsotericIDE#7]
Hi @Timwi !
I made a simple installer application for EsotericIDE just as a little project. As I don't see any licensing information for this, would it be okay to distribute the installer script and/or make it public on github?
Thanks!

**Comment by Timwi** [comment]
Thank you for bringing to my attention the lack of a license. I added the MIT license to this project. So yes, you’re free to do what you described. If it’s good, feel free to submit a pull request and I’ll take a look at it :)

**Comment by knthb** [comment]
My installer isn't great right now, but it's at [https://github.com/knth-b/EsotericIDE-Installer](https://github.com/knth-b/EsotericIDE-Installer)
