### ISSUE TITLE
Esolang Compilation Errors

### ISSUE THREAD

**Issue by Draco18s** [Timwi/EsotericIDE#9]
In trying to add my own language to the IDE I discovered that the IDE does not seem to have any method to handle compilation errors: that is, it assumes that all implemented languages will always compile successfully.

This is not true of Runic, which has 5 declared compilation error types (one of which will never be thrown as it is no longer relevant) not including `NONE` (i.e. a successful compile). In the event that the parser determines that the input source is invalid it cannot create a valid execution environment and spits out a `null`, which is returned by `ProgrammingLanguage.Compile`, resulting in the IDE displaying a NPE dialog box.

This is clearly less than idea, but I am unable to determine what I should do instead.

**Comment by Timwi** [comment]
The way to handle compilation errors is to throw a `CompileException`. The Parser for Sclipting makes use of that, so go take a look at that for an example.

**Comment by Draco18s** [comment]
Perfect! That's exactly what I needed, I just couldn't *find* it. I'm not familiar enough with the other languages here to determine which one could have compile problems or cause one to occur.

In retrospect, its right there in the project root. >_>

**Comment by Timwi** [comment]
BTW I’d be delighted to take a pull request for your esolang when you finish your interpreter :)

**Comment by Draco18s** [comment]
That's the plan! And it'll be double the fun when I find a bug and have to patch it. :D
